#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${REPO_ROOT}"

TS="${TS:-$(date +%Y%m%d_%H%M%S)}"
RUN_ID="${RUN_ID:-${TS}_off_policy_local_replica_256}"
LOG="${LOG:-/work5/jingwut/logs/waste_sd_${RUN_ID}.log}"

mkdir -p "$(dirname "${LOG}")"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" \
TMPDIR="${TMPDIR:-/work5/jingwut/tmp}" \
TEMP="${TEMP:-/work5/jingwut/tmp}" \
TMP="${TMP:-/work5/jingwut/tmp}" \
WASTE_SD_RAY_NOSET_VISIBLE_DEVICES="${WASTE_SD_RAY_NOSET_VISIBLE_DEVICES:-1}" \
WASTE_SD_RAY_TMP_DIR="${WASTE_SD_RAY_TMP_DIR:-/work5/jingwut/rwsd_${USER}_$RANDOM}" \
WASTE_SD_N_GPUS_PER_NODE="${WASTE_SD_N_GPUS_PER_NODE:-2}" \
WASTE_SD_NNODES="${WASTE_SD_NNODES:-1}" \
WASTE_SD_RESUME_MODE="${WASTE_SD_RESUME_MODE:-disable}" \
WASTE_SD_RESUME_FROM_PATH="${WASTE_SD_RESUME_FROM_PATH:-}" \
WASTE_SD_DEFAULT_LOCAL_DIR="${WASTE_SD_DEFAULT_LOCAL_DIR:-${REPO_ROOT}/checkpoints/waste_sd_${RUN_ID}}" \
WASTE_SD_PROJECT_NAME="${WASTE_SD_PROJECT_NAME:-waste_sd_backend_ab}" \
WASTE_SD_EXPERIMENT_NAME="${WASTE_SD_EXPERIMENT_NAME:-${RUN_ID}}" \
WASTE_SD_DEBUG="${WASTE_SD_DEBUG:-0}" \
WASTE_SD_TRAINER_LOGGER="${WASTE_SD_TRAINER_LOGGER:-console}" \
WASTE_SD_STUDENT_MODEL="${WASTE_SD_STUDENT_MODEL:-Qwen/Qwen2.5-0.5B}" \
WASTE_SD_TEACHER_MODEL="${WASTE_SD_TEACHER_MODEL:-Qwen/Qwen3-1.7B-Base}" \
WASTE_SD_TRAIN_FILE="${WASTE_SD_TRAIN_FILE:-/work5/jingwut/On-Policy-Distillation/data/gsm8k_gkd/train.parquet}" \
WASTE_SD_VAL_FILE="${WASTE_SD_VAL_FILE:-/work5/jingwut/On-Policy-Distillation/data/gsm8k_gkd/test.parquet}" \
WASTE_SD_TOTAL_TRAINING_STEPS="${WASTE_SD_TOTAL_TRAINING_STEPS:-30}" \
WASTE_SD_SAVE_FREQ="${WASTE_SD_SAVE_FREQ:--1}" \
WASTE_SD_TEST_FREQ="${WASTE_SD_TEST_FREQ:--1}" \
WASTE_SD_GAMMA="${WASTE_SD_GAMMA:-6}" \
WASTE_SD_ACTOR_LR="${WASTE_SD_ACTOR_LR:-5e-6}" \
WASTE_SD_TRAIN_BATCH_SIZE="${WASTE_SD_TRAIN_BATCH_SIZE:-6}" \
WASTE_SD_VAL_BATCH_SIZE="${WASTE_SD_VAL_BATCH_SIZE:-6}" \
WASTE_SD_PPO_MINI_BATCH_SIZE="${WASTE_SD_PPO_MINI_BATCH_SIZE:-6}" \
WASTE_SD_TEACHER_FORWARD_BACKEND=local_replica \
WASTE_SD_MAX_PROMPT_LENGTH=256 \
WASTE_SD_ROLLOUT_PROMPT_LENGTH=256 \
WASTE_SD_MAX_RESPONSE_LENGTH=256 \
WASTE_SD_ROLLOUT_RESPONSE_LENGTH=256 \
WASTE_SD_FILTER_OVERLONG_PROMPTS=true \
bash recipe/waste_sd/run_teacher_off_policy.sh 2>&1 | tee "${LOG}"

echo "LOG=${LOG}"
